sudo: required
language: node_js
node_js:
      - "8.14.0"
services:
  - docker

env:
  - DOCKER_IMAGE_NAME=webitel/kibana

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - kibana_get.sh
  - kibana_build.sh

install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME:6.5.4 .

script:
  - docker push $DOCKER_IMAGE_NAME:6.5.4
